-- FUNÇÕES NATIVAS

-- ISNULL - VERIFICA SE UM VALOR É NULL, SE FOR MOSTRA O SEGUDNO PARAMETRO
SELECT ISNULL(NULL, 5)

-- CONCAT - CONCATENA VARIAS STRINGS
SELECT CONCAT('nome', 'mais faladop')

-- CONCAT_WS - CONCATENA STRINGS COM UM SEPARADOR ESPECIFICADO
SELECT CONCAT_WS(',','Matheus', 'Albert')

-- REPLACE - SUBSTITUI TODAS AS OCORRENCIAS EM UM TEXTO POR OUTRA EXPRESSÃO
SELECT REPLACE('Aqui tem um texto', 'texto', 'texto substituido')

-- REPLICATE - REPLICA UM STRING N VEZES
SELECT 'TEST' + REPLICATE('.', 15)

-- CAST - CONVERTE TIPOS DE DADOS PARA OUTROS TIPOS DE DADOS

SELECT CAST(145 AS VARCHAR) AS CONVERTIDO

-- CONVERT - CAST MAIS SOFISTICADO

SELECT GETDATE() -- retorna a data atual

SELECT CONVERT(VARCHAR, GETDATE(), 101)


-- STRING_SPLIT - DIVIDE UMA STRING TENDO COMO BASE UM DELIMITADOR

SELECT * FROM STRING_SPLIT('Matheus Albert da Silva Araújo', ' ')
SELECT * FROM STRING_SPLIT('1,2,3,3,,5,4,6,57,5654', ',')

-- FUNÇÕES DE VALOR ESCALAR VS FUNÇÕES DE VALOR DE TABELA
 -- ESCALAR: RETORNAR UM VALOR
 -- TABELA: RETORNAR UMA TABELA, OU SEJA VÁRIOS VALORES

-- FUNÇÕES DE DATA

-- GETDATE - RETONAR DATA E HORA
SELECT GETDATE() 

-- DATEADD - ADCIONA DIAS, MESES OU ANOS A UMA DATA
SELECT DATEADD(YEAR, 2, GETDATE())

-- DATEDIF - RETORNA A DIFERENÇA DE DIA,HORAS, MESES OU ANOS ENTRE DUAS DATAS
SELECT DATEDIFF(HOUR, CAST('2002-11-16' AS DATE), GETDATE())

-- DAY, MONTH, YEAR - EXTRAI O DIA,MES OU ANO DE UMA DATA EM UM VALOR INTEIRO

SELECT DAY(GETDATE())
SELECT YEAR(GETDATE())

-- IS DATE - VERIFICA SE UM VALOR É UMA DATA

SELECT ISDATE('2025/02/22')

-- DATEPART - RETORNA UMA PARTE DE UMA DATA MAIS DETALHADAMENTE -WEEK, WEEKDAY, MILLISECONDS

SELECT DATEPART(WEEKDAY,GETDATE())

-- DATENAME - RETORNA O NOME DE UMA PARTE DA DATA

SELECT DATENAME(MONTH, GETDATE())

-- SUBSTRING - EXTRAI UMA PARTE DE UMA EXPRESSÃO - expressão, inicio, quantos vou pegar

SELECT SUBSTRING('NOME PARA TESTE',1,2)

-- (L,R)TRIM - REMOVE ESPAÇOS EM BRANCO DO INICIO E FIM DE UMA EXPRESSÃO

SELECT TRIM(' teste para espaços')

-- LEFT E RIGTH - PEGA UMA EXPRESSÃO DO INICIO OU FIM, X LETRAS

SELECT LEFT('TESTE LETRAS',4)

-- UPPER E LOWER - MAISCULAS E MINUSCULAS

SELECT UPPER('asdfkjasdfjasdfljs')

-- ´REPLACE - SUBSTITUI TODAS AS OCORRENCIAS DE UMA EXPRESSÃO POR OUTRA

SELECT REPLACE('teste de replace', 'de', 'pau')

-- CONCAT - CONCATENA STRINGS OU +

SELECT CONCAT('1' , ',')

-- LEN - COMPRIMENTO DE UMA STRING

SELECT LEN('sagagasdfasdfasdfasdfas')

-- REVERSE - INVERTE

SELECT REVERSE('sagagasdfasdfasdfasdfas')

-- REPLICATE - REPETE UM VALOR N VEZES

SELECT REPLICATE('.',100)

-- SPACE - CADEIA DE ESPAÇOS VAZIOS

SELECT 'OLA' + SPACE(10)

-- CHARINDEX - RETORNA A POSICAO DE UMA EXPRESSÃO PROCURADA

SELECT CHARINDEX('a', 'huihuhuhuhaijijoi')

-- FORMART - PARA FORMATAR CARACTERES

SELECT FORMAT(84987548540, '(##) #####-####')

-- STRING_AGG - CONCATENA OS VALORES DE UMA COLUNA EM UMA LINHA

-- STUFF - SUBSTITUI UMA CADEIA DE CARACTERES POR OUTRA

SELECT STUFF('Castelo do ratimbum', 1, 7, 'ROLA')

-- ISJSON - VERIFICAR SE JSON É VALIDO OU NAO
DECLARE @j NVARCHAR(MAX) = '{"id":2}'
SELECT ISJSON(@j)

SELECT JSON_VALUE(@j, '$.id')

-- CHOOSE - RETORNA A POSICAO DO INDICE ESPECIFICADO

SELECT CHOOSE(2,'Matheus', 'Albert', 'Arauojo')

-- IIF - OPERADOR TERNARIO
SELECT IIF(5 > 2, 'Verdadeiro', 'Falso')

-- COALESCE - RETORNA A PRIMEIRA EXPRESSAO QUE NAO É NULA
SELECT COALESCE(NULL, NULL, 'NULLO', NULL)

-- NULLIF - SE DUAS EXPRESSOES FOREM IGUAIS RETORNA NULL, SENÃO RETORNA O PRIMEIRO VALOR
SELECT NULLIF(1,0)

-- NEWID - RETORNA UM VALOR DE ID
SELECT NEWID()

-- ABS - VALOR ABSOLUTO
SELECT ABS(-45)

-- CELING - ARREDONDA O VALOR PARA CIMA
SELECT CEILING(145.8)

-- FLOOR - ARRDONDA O VALOR PARA BAIXO
SELECT FLOOR(145.9)

-- ROUND
SELECT ROUND(145.785, 2)

-- RAND - VALOR RANDOMICO
SELECT RAND()

SELECT CAST(78.547 AS DECIMAL(5,3))